name: Scrape KNMI 10 minute data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '1/5 * * * *'

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.is_template }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: "pip"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers
    - name: Install Playwright dependencies
      run: |
        shot-scraper install
    - name: Scrape
      run: |        
        shot-scraper javascript https://www.knmi.nl/nederland-nu/weer/waarnemingen '
        () => {
          function tableToObjects(table, timestamp) {
            const rows = Array.from(table.querySelectorAll("tr"));
            if (rows.length === 0) {
              return [];
            }
            const headers = Array.from(rows[0].querySelectorAll("th"))
              .map(headerCell => headerCell.textContent.trim());
            if (headers.length === 0) {
              return [];
            }
            const result = [];
            for (let i = 1; i < rows.length; i++) {
              const row = rows[i];
              const cells = Array.from(row.querySelectorAll("td"));
              if (cells.length === 0) {
                continue;
              }
              const rowObject = { timestamp: timestamp };
              headers.forEach((header, index) => {
                if (index < cells.length) {
                  rowObject[header] = cells[index].textContent.trim();
                }
              });
              result.push(rowObject);
            }
            return result;
          }

          function convertToISO(timestamp) {
            const cleanedTimestamp = timestamp.replace("Waarnemingen ", "").replace(" uur", "");
            const monthMapping = {
              "januari": "01", "februari": "02", "maart": "03", "april": "04",
              "mei": "05", "juni": "06", "juli": "07", "augustus": "08",
              "september": "09", "oktober": "10", "november": "11", "december": "12"
            };
            const [day, monthName, year, time] = cleanedTimestamp.split(" ");
            const month = monthMapping[monthName];
            const date = new Date(`${year}-${month}-${day}T${time}:00`);
            console.log(date);
            return date.toISOString();
          }

          console.log(document);
          const timestampElement = document.querySelector("#weather > div.columns.filled-main-content > div:nth-child(4) > div > div > h2");
          if (!timestampElement) {
            throw new Error("Timestamp element not found");
          }
          const timestamp = convertToISO(timestampElement.textContent.trim());
          return tableToObjects(document.querySelectorAll("table")[0], timestamp);
        }
        ' > knmi-waarnemingen.json
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
